### ISSUE TITLE
incorrect function input type

### ISSUE THREAD

**Issue by MHGolestani77** [hekmatinasser/jalali#5]
Hello
in the src/Traits/Creator.php file in line 171:
public static function parseFormat(string $format, string $datetime, bool $timezone = null): static
timezone defined as bool but timezone must be DateTimeZone or string.
thanks

@hekmatinasser

**Comment by hekmatinasser** [comment]
hello
fix this issues in version [x8.2.2](https://github.com/hekmatinasser/jalali/tree/x8.2.2)
